---
title: "Main"
output: pdf_document
---

```{r setup, include=FALSE}
pkgs <- c("keras", "lime", "tidyquant", "rsample", "recipes", "yardstick", "corrr","stringr")
install.packages(pkgs)
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(ggplot2)
library(tidyverse)
library(keras)
library(lime)
library(tidyquant)
library(rsample)
library(recipes)
library(yardstick)
library(corrr)
```


```{r}

#Fetch Data
gdp <- read.csv("data/GDP.csv")
cost <- read.csv("data/cost.csv")
nb <- read.csv("data/NB.csv")
LowerS <- read.csv("data/LowerS.csv")
percent_UP <- read.csv("data/percent_urban_population.csv")
procedures <- read.csv("data/procedures.csv")
sexratio <- read.csv("data/sexratio.csv")
time <- read.csv("data/time.csv")
countries <- read.delim("data/countries.txt", header = FALSE, sep = "\n")
EODB_index <- read.csv("data/EODB-index.csv")
```


```{r}
# Preprocess Data
cost1 <- cost %>%
  mutate(Cost = cost$Cost...Men....of.income.per.capita. , Country = cost$Economy , Year = cost$DB.Year) %>%
  select( Country, Year, Cost ) %>%
  drop_na() %>%
  filter(!Year %in% c(2019,2020,2005)) %>%
  mutate(Cost, Cost = ifelse(Cost>75,"High",ifelse(Cost>25,"Medium High",ifelse(Cost>10,"Medium Low","Low"))))


gdp1 <- gdp %>%
  select (Country.Code , Country.Name, X2000:X2018) %>%
  gather("Year","GDP",3:21) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  mutate ( Log_GDP = log(GDP)) %>%
  select(Country = Country.Name, Code = Country.Code, Year,Log_GDP) %>%
  filter(!Year %in% c(2000,2001,2002,2003,2004,2005))


nb1 <- nb %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  rowwise() %>%
  mutate(X2017,X2017 = mean(c(X2015,X2016),na.rm = TRUE)) %>%
  mutate(X2018, X2018 = mean(c(X2016,X2017),na.rm = TRUE)) %>%
  gather("Year","NB",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year,NB) #%>%
  #mutate(NB, NB = ifelse(NB>20000, "High",ifelse(NB>1000,"Medium","Low"))) 

LowerS1 <- LowerS %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","LowerSecondary",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, LowerSecondary)


percent_UP1 <- percent_UP %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","Percent_Urban_Population",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, Percent_Urban_Population)

procedures1 <- procedures %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","procedures",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, procedures)
  
sexratio1 <- sexratio %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  rowwise() %>%
  mutate(X2018,X2018 = mean(c(X2015,X2016),na.rm = TRUE)) %>%
  mutate(X2006,X2006 = mean(c(X2008,X2009),na.rm = TRUE)) %>%
  gather("Year","sexratio",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, sexratio)

time1 <- time %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","time_days",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, time_days)
   
EODB_index1 <- EODB_index %>%
  select (Jurisdiction, X2018:X2006) %>%
  gather("Year","EODB_index",2:14) %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Jurisdiction, Year, EODB_index) %>%
  mutate(Country, Country = str_trim(Country)) %>%
  arrange(desc(Year)) %>%
  arrange(Country) %>%
  rowwise() %>%
  mutate(EODB_index, EODB_index = ifelse(EODB_index!= "N/A", parse_number(EODB_index),NA ))


```

```{r}
#Merge
Xian <- cost1
Xian <- merge(Xian,gdp1,by = c("Country","Year"), all.y = TRUE)
Xian <- merge(Xian,procedures1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,time1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,sexratio1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,nb1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,LowerS1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,percent_UP1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,EODB_index1,by = c("Country","Year"),all.x = TRUE)

```



```{r}
#REPLACE NA VALUES AND REMOVE OTHER JUNK

Xian1 <- Xian %>%
  filter(Country %in% countries$V1 )  %>%
  arrange(desc(Year)) %>%
  arrange(Country) 

Xian <- Xian1 %>%
  mutate(index = seq(1,length(Xian1$Year),1)) %>%
  filter(index <= 2080 ) %>%
  select(index,Country,Code,Year,everything()) 


### Cost
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(Cost)), bestval = "") %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
#for few costs missing
for (i in 1:length(Xian$Cost)) {
  if (is.na(Xian$Cost[i]) == TRUE) {
    if (Xian$Country[i] == Xian$Country[i-1]){
    Xian$Cost[i] = Xian$Cost[i-1]}
  }
}
#For all costs missing
Xian <- Xian %>%
  mutate(Country, Cost = ifelse(Country == "Liechtenstein","Medium High",Cost ))

### GDP
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(Log_GDP)), bestval = max(Log_GDP, na.rm = TRUE))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(Log_GDP) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( Log_GDP, Log_GDP = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , Log_GDP , Log_GDP) ) ) 



### Procedures
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(procedures)), bestval = max(procedures, na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(procedures) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( procedures, procedures = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , procedures, procedures) ) ) 



### Time_days
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(time_days)), bestval = mean(time_days, na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(time_days) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( time_days, time_days = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , time_days, time_days) ) ) 


### sexratio
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(sexratio)), bestval = mean(Xian$sexratio, na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(sexratio) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( sexratio, sexratio = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , natest$bestval[which(natest$Country==Country)], sexratio) ) ) 


### NB and convert to category
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(NB)), bestval = mean(NB,na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(NB) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( NB, NB = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , mean(Xian$NB,na.rm = TRUE), NB) ) )  %>%
  mutate(NB, NB = ifelse(NB>20000, "High",ifelse(NB>1000,"Medium","Low"))) 


### Lower Secondary
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(LowerSecondary)), bestval = max(LowerSecondary,na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(LowerSecondary) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( LowerSecondary, LowerSecondary = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , mean(Xian$LowerSecondary,na.rm = TRUE), LowerSecondary) ) ) 


### Percent Urban Population
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(Percent_Urban_Population)), bestval = max(Percent_Urban_Population,na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(Percent_Urban_Population) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( Percent_Urban_Population, Percent_Urban_Population = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , mean(Xian$Percent_Urban_Population,na.rm = TRUE), Percent_Urban_Population) ) ) 


### EODB_Index
natest <- Xian %>%
  group_by(Country) %>%
  summarise(count = sum(is.na(EODB_index)), bestval = max(EODB_index,na.rm = TRUE)) %>%
  mutate(Method = ifelse(count>0 , ifelse(count==13,"All","Few") , "NAN"))
Xian <- Xian %>%
  mutate(HasNA = ifelse(is.na(EODB_index) == TRUE,"Yes","No")) %>%
  rowwise() %>%
  mutate(Method = ifelse(HasNA == "Yes", ifelse(natest$count[which(natest$Country==Country)]<13, "Few" , "All"), "NAN")) %>%
  mutate( EODB_index, EODB_index = ifelse( Method=="Few" , natest$bestval[which(natest$Country==Country)], ifelse(Method == "All" , mean(Xian$EODB_index,na.rm = TRUE), EODB_index) ) )

### Generate outcome variables
Xian$Y <- as.numeric(cut(Xian$EODB_index, 2))
Xian <- Xian  %>%
  select(-HasNA,-Method) 

str(Xian)


```

```{r}
#Test and train data
train_data <- Xian %>%
  filter(Year != "2018") %>%
  mutate(Country, Country = as.character(Country)) %>%
  select(-index,-Code,-Year,-EODB_index)

str(train_data)
test_data <- Xian %>%
  filter(Year == "2018") %>%
  mutate(Country, Country = as.character(Country)) %>%
  select(-index,-Code,-Year,-EODB_index)

str(test_data)

```

```{r}
#Recipe for baking
rec_obj <- recipe(Y ~ ., data = train_data) %>%
  step_dummy(Country, one_hot = TRUE) %>%
  step_dummy(Cost, one_hot = TRUE) %>%
  step_dummy(NB, one_hot = TRUE) %>%
  step_center(all_predictors(), -all_outcomes()) %>%
  step_scale(all_predictors(), -all_outcomes()) %>%
  prep(data = train_data)
  
rec_obj



#Bake both sets for predictors
Xtrain <- bake(rec_obj, new_data = train_data) %>% select(-Y) 
Xtest  <- bake(rec_obj, new_data = test_data) %>% select(-Y) 

#str(Xtrain)
#glimpse(Xtrain)
# Response variables both sets
Ytrain <- to_categorical(train_data$Y)
Ytest  <- to_categorical(test_data$Y)

#Note Length of target labels is 11 after OHE due to having novalue also as a column 

```



```{r}

# Building our Artificial Neural Network
model <- keras_model_sequential()

model %>% 
  # First hidden layer
  layer_dense(units= 80, activation= "relu", kernel_initializer = "uniform",input_shape = ncol(Xtrain)) %>% 
  # Output layer
  layer_dense(units= 3, kernel_initializer = "uniform",activation = "softmax") 
  


# Print a summary of a model
summary(model)

# Get model configuration
get_config(model)

# Get layer configuration
get_layer(model, index = 1)

# List the model's layers
model$layers

# List the input tensors
model$inputs

# List the output tensors
model$outputs


# Compile ANN
model %>%  compile(optimizer = 'adam', loss  = 'binary_crossentropy', metrics   = 'accuracy' )



```






```{r}

# Store the fitting history in `history` 
history <- model %>% fit(
     as.matrix(Xtrain), 
     as.matrix(Ytrain), 
     epochs = 20,
     batch_size = 32 , 
     validation_split = 0.2
 )

# Plot the history
plot(history)



```




```{r}

# Predict the classes for the test data
pred <- model %>% predict_classes(as.matrix(Xtest))

# Confusion matrix
table(actual=test_data$Y, pred)


#Predict probabilities
YProb  <- predict_proba(object = model, x = as.matrix(Xtest))

colnames(YProb) <- c("none","easy","noteasy")

YProb <- as.data.frame(YProb)
YProb <- YProb %>%
  rowwise() %>%
  mutate(asdad =  max(none,easy,noteasy)) 

YProb$Predicted = as.vector(pred)
YProb$Country = test_data$Country


Top_1_cat <- YProb %>%
  filter(Predicted == 1) %>%
  arrange(desc(asdad)) %>%
 select(Country)

Top_2_cat <- YProb %>%
  filter(Predicted == 2) %>%
  arrange(asdad) %>%
 select(Country)

test <- as.data.frame(bind_rows(Top_1_cat, Top_2_cat))

test <- test %>%
  mutate(Rank = seq(1,length(test$Country),1))

YClassProb <- predict_classes(object = model, x = as.matrix(Xtest)) %>% as.vector()

estimates_keras_tbl <- tibble(
  truth      = as.factor(Ytest) %>% fct_recode(yes = "1", no = "0"),
  estimate   = as.factor(pred) %>% fct_recode(yes = "1", no = "0"),
  class_prob = YClassProb
)

estimates_keras_tbl
```




```{r}








```














