---
title: "Ellen"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### before pushing always pulling

#### Shiny Visualization
```{r}
library(shiny)
library(shinydashboard)
## load data 
countries <- read.delim("Data/countries.txt")

```

```{r}
header <- dashboardHeader(
  title = "Genius Ashish",
  titleWidth = 250
)

sidebar <- dashboardSidebar(
  sidebarMenuOutput('menu'))

body <- dashboardBody(
  tabItems(
    # homepage tab content
    tabItem(tabName="hp"),
    
    ## second tab content
    tabItem(tabName="countryselect",
            fluidRow(
              box(
                title = "Easiness Rank"),
              box(
                title = "Urban Population",
                plotOutput("plot1",height = 250)
                 ),
              box(
                title = "Whatever Ashish Want"
                ),
              box(
                title = "Index Table",
                plotOutput("plot2",height=600)
                 ),
             box(
                title ="Ranking Trend",
                plotOutput("plot3",height =300)
                 ),
              box(
                title = "Correlation",
                plotOutput("plot4",height = 300)
                 )
                 )
    
  )))


   


ui <- dashboardPage(header,sidebar,body)
server <- function(input, output){
  output$menu<-renderMenu({
    sidebarMenu(
    menuItem(
      text='Homepage',
      tabName = 'hp'),
    menuItem(
      tabName = "countryselect",
      selectInput(
        "select",
        label = ("Select a Country"),
        choices = Xian$Country)
      )
 )
  })
}
shinyApp(ui,server)

```

