---
title: "John"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# Load Libraries
library(ggplot2)
library(tidyverse)
library(lubridate)
library(forcats)
library(scales)
library(ggforce)

```

```{r}

#Fetch Data
gdp <- read.csv("data/GDP.csv")
cost <- read.csv("data/cost.csv")
nb <- read.csv("data/NB.csv")
LowerS <- read.csv("data/LowerS.csv")
percent_UP <- read.csv("data/percent_urban_population.csv")
procedures <- read.csv("data/procedures.csv")
sexratio <- read.csv("data/sexratio.csv")
time <- read.csv("data/time.csv")
countries <- read.delim("data/countries.txt", header = FALSE, sep = "\n")
EODB_index <- read.csv("data/EODB-index.csv")
```


```{r}
# Preprocess Data
cost1 <- cost %>%
  mutate(Cost = cost$Cost...Men....of.income.per.capita. , Country = cost$Economy , Year = cost$DB.Year) %>%
  select( Country, Year, Cost ) %>%
  drop_na() %>%
  filter(!Year %in% c(2019,2020,2005)) %>%
  mutate(Cost, Cost = ifelse(Cost>75,"High",ifelse(Cost>25,"Medium High",ifelse(Cost>10,"Medium Low","Low"))))


gdp1 <- gdp %>%
  select (Country.Code , Country.Name, X2000:X2018) %>%
  gather("Year","GDP",3:21) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  mutate ( Log_GDP = log(GDP)) %>%
  select(Country = Country.Name, Code = Country.Code, Year,Log_GDP) %>%
  filter(!Year %in% c(2000,2001,2002,2003,2004,2005))


nb1 <- nb %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  rowwise() %>%
  mutate(X2017,X2017 = mean(c(X2015,X2016),na.rm = TRUE)) %>%
  mutate(X2018, X2018 = mean(c(X2016,X2017),na.rm = TRUE)) %>%
  gather("Year","NB",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year,NB) %>%
  mutate(NB, NB = ifelse(NB>20000, "High",ifelse(NB>1000,"Medium","Low")))

LowerS1 <- LowerS %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","LowerSecondary",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, LowerSecondary)

percent_UP1 <- percent_UP %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","Percent_Urban_Population",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, Percent_Urban_Population)

procedures1 <- procedures %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","procedures",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, procedures)
  
sexratio1 <- sexratio %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  rowwise() %>%
  mutate(X2018,X2018 = mean(c(X2015,X2016),na.rm = TRUE)) %>%
  mutate(X2006,X2006 = mean(c(X2008,X2009),na.rm = TRUE)) %>%
  gather("Year","sexratio",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, sexratio)

time1 <- time %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","time_days",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Year, time_days)
   
EODB_index1 <- EODB_index %>%
  select (Jurisdiction, X2018:X2006) %>%
  gather("Year","EODB_index",2:14) %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Jurisdiction, Year, EODB_index) %>%
  mutate(Country, Country = str_trim(Country)) %>%
  arrange(desc(Year)) %>%
  arrange(Country) %>%
  rowwise() %>%
  mutate(EODB_index, EODB_index = ifelse(EODB_index!= "N/A", parse_number(EODB_index),NA ))


```

```{r}
#Merge
Xian <- cost1
Xian <- merge(Xian,gdp1,by = c("Country","Year"), all.y = TRUE)
Xian <- merge(Xian,procedures1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,time1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,sexratio1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,nb1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,LowerS1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,percent_UP1,by = c("Country","Year"),all.y = TRUE)
Xian <- merge(Xian,EODB_index1,by = c("Country","Year"),all.x = TRUE)

```

```{r}


```

```{r}

## Urban Population percent semi pie chart for each country (Xian)

Test1 <- Xian %>%
  group_by(Country) %>% summarize(Urban_Pop_Percent=mean(Percent_Urban_Population)) %>%
  filter(Country=="Afghanistan")


## spc <- ggplot(Xian.Afghanistan, aes(x = "Afghanistan", y = Urban_Pop_Percent)) +
## geom_bar(width = 1, stat = "identity", color = "white") +
## spc

## pie <- spc + coord_polar("y", start=0)
## pie

Test3 <- Test2 %>%
  mutate(angle = cumsum(Urban_Pop_Percent - 0.5 * Urban_Pop_Percent))

ggplot(Test2, aes(x = Country, y = Urban_Pop_Percent)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(label = Country), color = "white")+
  theme_void()


## works but this one shows the numbers/percentages on the wrong part
mycols <- c("#0073C2FF", "#EFC000FF")
ggplot(Test3, aes(x = 2, y = Urban_Pop_Percent, fill = Country)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0, direction = 1)+
  geom_text(aes(y = angle, label = paste0(round(Urban_Pop_Percent,2), '%')))+
  scale_fill_manual(values = mycols) +
  theme_void() +
  xlim(0.5, 2.5)


Test3 %>%
  mutate_at(vars(starts_with("y")), rescale, to=pi*c(-.5,.5), from=0:1) %>%
  ggplot + 
  geom_bar(aes(x0 = 0, y0 = 0, r0 = .5, r = 1, start = ymin, end = ymax, fill=Party)) + 
  coord_fixed() 


```

```{r}

## just experimenting here

mycols <- c("#0073C2FF", "#0073C2FF")
ggplot(Test3, aes(x = 2, y = Urban_Pop_Percent, fill = Country)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0, direction = 1)+
  geom_text(aes(y = angle, label = paste0(round(Urban_Pop_Percent, 2), '%')))+
  scale_fill_manual(values = mycols) +
  theme_void() +
  xlim(0.5, 2.5) 



```

```{r}

## can't use numeric functions like mean fcn on a factor like cost because it is in string format (it's words, not numbers); so in this case, just use the entire Xian df

Test_Cost <- Xian %>%
  group_by(Country) %>% summarize(Cost_Index=(Cost)) %>%
  filter(Country=="Afghanistan")


```

```{r}

Test_GDP <- Xian %>%
  group_by(Country) %>% summarize(GDP_Log=mean(Log_GDP)) %>%
  filter(Country=="Afghanistan")



```

```{r}

## experimenting, trying to do some ggplot for Cost factor/index in the Xian df

## mycols <- c("#0073C2FF", "#EFC000FF")
ggplot(Xian, aes(x = 2, y = Cost, fill = Country)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = 0, direction = 1)+
  ## geom_text(aes(y = angle, label = paste0(round(Cost,2), '%')))+
  scale_fill_manual(values = mycols) +
  theme_void() +
  xlim(0.5, 2.5)


```

```{r}

```

```{r}

```

```{r}

```

