---
title: "Nita"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkgs <- c("keras", "lime", "tidyquant", "rsample", "recipes", "yardstick", "corrr")
install.packages(pkgs)
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(keras)
library(lime)
library(tidyquant)
library(rsample)
library(recipes)
library(yardstick)
library(corrr)
```

```{r}
LowerS <- read.csv("data/LowerS.csv")
percent_UP <- read.csv("data/percent_urban_population.csv")
procedures <- read.csv("data/procedures.csv")
sexratio <- read.csv("data/sexratio.csv")
time <- read.csv("data/time.csv")
EODB_index <- read.csv("data/EODB-index.csv")


LowerS1 <- LowerS %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","LowerSecondary",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Code = Country.Code, Year, LowerSecondary)

percent_UP1 <- percent_UP %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","Percent_Urban_Population",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Code = Country.Code, Year, Percent_Urban_Population)

procedures1 <- procedures %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","procedures",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Code = Country.Code, Year, procedures)
  
sexratio1 <- sexratio %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","sexratio",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Code = Country.Code, Year, sexratio)

time1 <- time %>%
  select (Country.Code , Country.Name, X2006:X2018) %>%
  gather("Year","time_days",3:15) %>%
  arrange(desc(Year)) %>%
  arrange(Country.Name)  %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Country.Name, Code = Country.Code, Year, time_days)
  
EODB_index1 <- EODB_index %>%
  select (Jurisdiction, X2018:X2006) %>%
  gather("Year","EODB_index",2:14) %>%
  mutate(Year, Year = str_replace(Year, "X", "")) %>%
  select(Country = Jurisdiction, Year, EODB_index) %>%
  filter((Year == 2018))

```



```{r}
#missing_values in cost all filled
for (i in 1:length(Xian1$Cost)) {
  if (is.na(Xian1$Cost[i]) == TRUE) {
    if (Xian1$Country[i] == Xian1$Country[i-1]){
    Xian1$Cost[i] = Xian1$Cost[i-1]}
  }
}
for (i in length(Xian1$Cost):1) {
  if (is.na(Xian1$Cost[i]) == TRUE) {
    if (Xian1$Country[i] == Xian1$Country[i+1]){
    Xian1$Cost[i] = Xian1$Cost[i+1]}
  }
}
xian2 <- Xian1 %>%
  filter(is.na(Cost) == TRUE)
```

```{r}
#missing_values in LowerS
for (i in 2:length(Xian1$LowerSecondary)) {
  if (is.na(Xian1$LowerSecondary[i]) == TRUE) {
    if (Xian1$Country[i] == Xian1$Country[i-1]){
    Xian1$LowerSecondary[i] = Xian1$LowerSecondary[i-1]}
  }
}
for (i in length(Xian1$LowerSecondary):1) {
  if (is.na(Xian1$LowerSecondary[i]) == TRUE) {
    if (Xian1$Country[i] == Xian1$Country[i+1]){
    Xian1$LowerSecondary[i] = Xian1$LowerSecondary[i+1]}
  }
}
xian2 <- Xian1 %>%
  filter(is.na(LowerSecondary) == TRUE) %>%
  select(Country, LowerSecondary, EODB_index) %>%
  group_by(Country) %>%
  summarise(size = n())
#15 countries has missing values for all the years
```


```{r}
##Homepage Heat World Map
countries <- Xian %>%
  group_by(Code) %>%
  summarise(size = n())
test1 <- cbind(test, countries$Code)
install.packages("rworldmap")
library(rworldmap)
mapped_data <- joinCountryData2Map(test1, joinCode = "ISO3", 
    nameJoinColumn = "countries$Code")
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")
heatworldmap <- mapCountryData(mapped_data, nameColumnToPlot = "Rank", colourPalette=c('#1E6C03', '#E5FEDC'), addLegend='TRUE', borderCol = "grey", mapTitle = "Rank - Ease Of Doing Business")
```

```{r}
##Homepage trending line for 8 countries
index11 <- Xian %>%
  group_by(Country) %>%
  summarise(Year_top = min(EODB_index), Year_bott = max(EODB_index))
plot_countries = c('New Zealand', 'Finland', 'Norway', 'Canada', 'Eritrea', 'Central African Republic', 'Iraq', 'Chad')
bottom_countries = c('Eritrea', 'Equatorial Guinea', 'Central African Republic', 'Iraq', 'Chad')
index1 <- Xian %>%
  filter(Country %in% plot_countries) %>%
  select(Country, Year, EODB_index)
trending_line <- ggplot(data=index1, aes(x=Year, y=EODB_index, color = Country, group = Country)) +geom_line() + geom_point() + labs(x="Year", y = "rank of ease of doing business")
```

```{r}
#Individual page for urban population percentage
UP <- Xian %>%
  group_by(Country) %>%
  summarise(UP_perc = mean(Percent_Urban_Population)) %>%
  mutate(NUP_perc = 100 - UP_perc)

UP1 <- UP %>%
  gather("UP_prec","NUP_prec",2:3)  %>%
  arrange(Country) %>%
  filter(Country == "Afghanistan")
colnames(UP1) <- c("Country","Class","Perc")
UP1$ymax = cumsum(UP1$Perc)
UP1$ymin = c(0, head(UP1$ymax, n= -1))


ggplot(UP1, aes(x = 2, y = Perc, fill = Class)) +
  geom_bar(stat = "identity", color = "white") +
  coord_polar(theta = "y", start = -pi/2)+
  geom_text(aes(y = round(Perc), label = round(Perc))) +
  theme_void()+xlim(0.5, 2.5)

library(ggforce)
library(scales)
UP1 %>%
  mutate_at(vars(starts_with("y")), rescale, to=pi*c(-.5,.5), from=0:1) %>%
  ggplot + 
  geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = .5, r = 1, start = ymin , end = ymax ,fill=Class)) + 
  coord_fixed() 

##Individual page for GDP Trending line
gdpline <- Xian %>%
  select (Country, Year, Log_GDP) %>%
  mutate (GDP = exp(Log_GDP)) %>%
  filter(Country == 'Afghanistan')
gdp_plot <- ggplot(data = gdpline, aes(x = Year, y = GDP, group = 1)) + geom_line() + geom_point()
```













